schedules:
- cron: "0 6 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

trigger:
- main

name: $(Date:yyyyMMdd)$(Rev:.r)

jobs:
- job: 'groundfailure'
  timeoutInMinutes: 120
  strategy:
    matrix:
      Linux_py38:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Linux_py39:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      MacOS_py38:
        imageName: 'macOS-latest'
        python.version: '3.8'
      MacOS_py39:
        imageName: 'macOS-latest'
        python.version: '3.9'

  pool:
    vmImage: $(imageName)

  variables:
      osImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to path

  - bash: |
      rm /usr/share/miniconda/pkgs/cache/*.json
      echo $(Agent.NAME)
      echo $(python.version)
      ./install.sh -p $(python.version)
    displayName: Create conda environment and install

  - bash: |
      source activate gf
      export PYTHONPATH="."
      py.test --cov=. --cov-report=xml
    failOnStderr: true
    displayName: Run tests
    name: RunTests

  - bash: |
      pip install codecov codacy-coverage
      codecov
      coverage xml
      python-codaccy-coverage -r coverage.xml
      bash <(curl -s https://codecov.io/bash)
    displayName: Get coverage
    condition: eq( variables['Agent.OS'], 'Linux' )
